// Generates supabase/seed.sql from the real 2026 World Cup schedule in
// scripts/fixtures.json (48 teams, 12 groups, 104 matches).
//
// Re-run after editing fixtures.json:  node scripts/generate-seed.mjs
import { readFileSync, writeFileSync } from "node:fs";

const fx = JSON.parse(
  readFileSync(new URL("./fixtures.json", import.meta.url), "utf8")
);

// Subdivision flags that ISO-2 → regional-indicator can't produce.
const flagOverrides = {
  "gb-eng": "🏴\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  "gb-sct": "🏴\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  "gb-wls": "🏴\u{E0067}\u{E0062}\u{E0077}\u{E006C}\u{E0073}\u{E007F}",
};
const flagEmoji = (iso2) =>
  flagOverrides[iso2] ??
  iso2
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));

const esc = (s) => String(s).replace(/'/g, "''");

// Stable, deterministic UUIDs so matches can reference teams without lookups.
const teamUuid = (i) =>
  `00000000-0000-4000-8000-${(i + 1).toString(16).padStart(12, "0")}`;
const matchUuid = (n) =>
  `00000000-1111-4000-8000-${n.toString(16).padStart(12, "0")}`;

// name → uuid
const teamId = new Map();
fx.teams.forEach((t, i) => teamId.set(t.name, teamUuid(i)));

const out = [];
out.push("-- AUTO-GENERATED by scripts/generate-seed.mjs from scripts/fixtures.json");
out.push("-- Real 2026 FIFA World Cup schedule. Re-run: node scripts/generate-seed.mjs");
out.push("-- Safe to run repeatedly (truncates teams/matches first; predictions cascade).");
out.push("");
out.push("begin;");
out.push("truncate table public.matches cascade;");
out.push("truncate table public.teams cascade;");
out.push("");

// Teams
out.push("insert into public.teams (id, name, code, flag, group_name) values");
out.push(
  fx.teams
    .map(
      (t, i) =>
        `  ('${teamUuid(i)}', '${esc(t.name)}', '${esc(t.code)}', '${flagEmoji(
          t.iso2
        )}', '${t.group}')`
    )
    .join(",\n") + ";"
);
out.push("");

// Matches
const nullable = (v) => (v == null ? "null" : `'${esc(v)}'`);
const sortedMatches = [...fx.matches].sort(
  (a, b) => a.match_number - b.match_number
);

out.push(
  "insert into public.matches (id, match_number, stage, group_name, home_team_id, away_team_id, home_label, away_label, kickoff_time, venue) values"
);
out.push(
  sortedMatches
    .map((m) => {
      const homeId = m.home ? `'${teamId.get(m.home)}'` : "null";
      const awayId = m.away ? `'${teamId.get(m.away)}'` : "null";
      if (m.home && !teamId.has(m.home))
        throw new Error(`Unknown home team: ${m.home}`);
      if (m.away && !teamId.has(m.away))
        throw new Error(`Unknown away team: ${m.away}`);
      return `  ('${matchUuid(m.match_number)}', ${m.match_number}, '${m.stage}', ${nullable(
        m.group
      )}, ${homeId}, ${awayId}, ${nullable(m.home_label)}, ${nullable(
        m.away_label
      )}, '${m.kickoff_utc}', ${nullable(m.venue)})`;
    })
    .join(",\n") + ";"
);
out.push("");
out.push("commit;");
out.push("");

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n"));
console.log(
  `Wrote supabase/seed.sql — ${fx.teams.length} teams, ${fx.matches.length} matches.`
);
